# Site settings
title: Zenodo Auto Serch Test Website
description: JZenodo Automation is a Python script that connects to the Zenodo API to automate downloading files linked to two search criteria (author and community).
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yair Rodríguez de la Peña
user_description: I'm a test xxxxx, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Test Software Engineer
email: testtt@gmail.com
# twitter_username: lorem_ipsum
instagram_username: YairRodz
facebook_username: YairRodz
linkedin_username: YairRodz
github_username:  YairRodz
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

